yolo_object_tracker:
  ros__parameters:
    color_topic: /head_camera/color/image_raw
    depth_topic: /head_camera/aligned_depth_to_color/image_raw
    camera_info_topic: /head_camera/color/camera_info
    selected_mask_topic: /selected_object_mask
    model: models/yolo/yolo11n.pt
    tracker: bytetrack.yaml
    device: auto
    image_size: 1280
    confidence_threshold: 0.35
    iou_threshold: 0.55
    maximum_inference_rate: 30.0
    depth_scale: 0.001
    minimum_depth: 0.15
    maximum_depth: 2.5
    allowed_classes: ['*']
